### ISSUE TITLE
Parking Machine Kit Despawns when placed even inside a territory 

### ISSUE THREAD

**Issue by BarricadeBandit** [Krypton91/GarageMod#4]
I'm not really too sure why this is happening The Parking machine is inside my Types.XML file and i cant seem to find any other fix for the issue 

If anybody knows why and is able to help me out that would be great!

**Comment by Krypton91** [comment]
Hello, not a problem of the mod you need to follow the instructions on steam! insert the Machine self into your Types.xml & problem solved!
